### ISSUE TITLE
Add Stats

### ISSUE THREAD

**Issue by Freddie-Banks** [LukasJK/vAMSYSissues#123]
Could airport stats be added into VDS? Would provide the OMs with Focus Airport ideas.

**Comment by LukasJK** [comment]
What stat are we talking about? Departures from airport X in X days?

**Comment by Freddie-Banks** [comment]
I mean it would have a running total of flights in and out of X Airport. Which would update on a daily basis. For example it would be like the stats that your provided in the excels but would be constantly up to date.

**Comment by LukasJK** [comment]
Total? Since the beginning of time?

**Comment by Freddie-Banks** [comment]
Yes, I think that would be best

**Comment by LukasJK** [comment]
moved to asana
