### ISSUE TITLE
VDS 1.1 Request

### ISSUE THREAD

**Issue by Chris-Chadwick** [LukasJK/vAMSYSissues#143]
I have two requests for VDS if I may; 
First, Could we have an IATA list in route editing part, it might be easier for new AM's to find the airport they are after when using LIDO. Possibly could edit the search form to search for IATA codes as well - it only appears to like airport names. Which brings me to my second question...
Could the OM's have a search in the top menu to manually search for a specific airport rather than going through the areas trying to find it.

**Comment by LukasJK** [comment]
Moved to Asana
