### ISSUE TITLE
Route reporting

### ISSUE THREAD

**Issue by soferek** [LukasJK/vAMSYSissues#17]
Could be nice to be able to replay to user and ask why he/she think the route is incorrect. Especially when there is not additional comments. Will help to reduce future tickets from such users if they know that for example route was ok and they just did not react disclaimer

**Comment by LukasJK** [comment]
Could adding a reason field in the route report box and prompting people to fill it, help?
Long-term goal is to move all invalid route reporting to VDS, where AMs would review it

**Comment by soferek** [comment]
Is system cannot add user ticket with user email ??this way when I replay to them they know why and what happened with they route report,  At this point I have reported few incomplete routes my self and as I haven't got replay I give up doing it .. which we don't want to happen are we ?I think the user need to have some kind of feedback to feel needed... and they could replay to ticket via email if discussion needed. or encourage to log in to ticket system to replay..

**Comment by LukasJK** [comment]
I can add the email address to the ticket we receive for route reports, but in order to reply, you will need to do so via your e-mail - i.e. it's not possible to reply via tickets, as that's not how they submit it and most likely don't have osticket account

**Comment by soferek** [comment]
Well email address. Would be absolutely fine. Because even today I had ticket with route which passed AIRAC 1605 validation and I have no clue why it was reported.

**Comment by soferek** [comment]
this is very good example. 

http://www.vryr.eu/support/scp/tickets.php?id=1050

why we need to be able to replay to this tickets :>
