### ISSUE TITLE
VDS delete confirmation

### ISSUE THREAD

**Issue by soferek** [LukasJK/vAMSYSissues#22]
There is no confirmation (double asking) when deleting (pressing wrong button) to delete areas/airports

**Comment by LukasJK** [comment]
I'm getting confirmation pop-ups. Are you on Internet Explorer?

**Comment by soferek** [comment]
I give it up as per your advise. I'm on chrome last month or so .

**Comment by LukasJK** [comment]
And you don't get this:
https://gyazo.com/c60c092135e1422ece913b40aeb43320
when clicking delete at https://vds.vamsys.io/aircraft

**Comment by soferek** [comment]
I'm getting that now. But when initially I have deleted all areas as I have done them wrong it didn't asked me even ones that is why I have open this. And I did use chrome at that time. Maybe because it wasn't implemented yet :)

**Comment by LukasJK** [comment]
And you get in areas now too?

**Comment by soferek** [comment]
Yes that is correct
