### ISSUE TITLE
VDS Add IATA / ICAO code to airports names in the route list

### ISSUE THREAD

**Issue by soferek** [LukasJK/vAMSYSissues#24]

**Comment by LukasJK** [comment]
Which page?

**Comment by soferek** [comment]
On dashboard press routes next to pairs and routes itself there..or that need to be used too boxes to search airports ?

**Comment by LukasJK** [comment]
ICAO/IATA exists when you click on the + button by the route;
The list is still searchable by ICAO IATA even it it's not shown.
