### ISSUE TITLE
VDS Area dashboard error

### ISSUE THREAD

**Issue by Chris-Chadwick** [LukasJK/vAMSYSissues#25]
Only error i have found so far is a typing error in the route update, should say Flight not Cost
http://prntscr.com/b4c0nh

**Comment by soferek** [comment]
when I click area, it doesn't work ?? https://vds.vamsys.io/areas/dashboard/25

is that for AM or this is for OM ?

**Comment by Chris-Chadwick** [comment]
I think its is simple hyperlink error, probably should read https://vds.vamsys.io/areas/25

**Comment by LukasJK** [comment]
Fixed in LukasJK/vAMSYSv2#7299406
