### ISSUE TITLE
Broken VDS

### ISSUE THREAD

**Issue by soferek** [LukasJK/vAMSYSissues#28]
https://vds.vamsys.io/routes/10140/edit

**Comment by LukasJK** [comment]
It's because the route has already been edited. Did you click the back button?

**Comment by LukasJK** [comment]
Disregard. What was the flight time you were putting in?

**Comment by soferek** [comment]
I have used "back" and I have put 3 digit time. And 2 digit distance

**Comment by LukasJK** [comment]
Do you remember what was the time you put in?
How come it was 3 digits? I thought OFP always has 4 in the Fuel Trip column

**Comment by soferek** [comment]
Don't remember time but I was just testing. Putting silly time and silly distance. And trying to reedit. Yes on ofp time is 4 digit 0234 but I I put manually I will obviously ignore zero and put 234. I guess everyone who doesn't copy will do this way.

**Comment by LukasJK** [comment]
Good point. Should be fixed now.
