### ISSUE TITLE
VDS route parsing and formatting 

### ISSUE THREAD

**Issue by soferek** [LukasJK/vAMSYSissues#59]
Is VDS could highlight (put on red) words with numbers in routes field first and last word/point? Which  will highlight when someone puts star or sid as they have numbers in names . Maybe not allowing to update route or second confirmation if there are any digits found in points I mean FIRST and LAST word/point as obviously routes have numbers. Maybe that could help with routes when ppl don't remove spaces and u will end up with two rows. Because first or second row will still have some point/routes with numbers in the word witch could potentially highlight wrong format of route input. 

Hope that makes sense 

And is it possible that VDS can remove or again highlight "space" sight at beginning of the route ? As I have catch my self they because I don't know when exactly beginning of the row is I had to double check if there it space on the beginning of the route.

**Comment by LukasJK** [comment]
Is it relevant? As per skype blast :
[17:13:19] Lukas Jankauskas: 
EGSS/04 CLN4S CLN M84 NONVA UM84 KONAN UL607 KOK UM150 UTABA UM738
UNTAD UQ333 DIKEM Z905 VIC LIPH/07gets turned to
CLN M84 NONVA UM84 KONAN UL607 KOK UM150 UTABA UM738 UNTAD UQ333 DIKEM Z905 VIC
removes all the linebreaks and stuff
