### ISSUE TITLE
Bulletin idea 

### ISSUE THREAD

**Issue by Freddie-Banks** [LukasJK/vAMSYSissues#77]
@LukasJK  Possible or not? An OM post a bulletin which will appear here? https://gyazo.com/d6375586c918b01dc096a9a74c15617e
Like the text you (lukas) have put in about beta
Can an OM do something like that? Post info for all OMs eg deadlines etc

**Comment by LukasJK** [comment]
Yes. Do you want global message only? With expiry date/time?

**Comment by Freddie-Banks** [comment]
Yes, pretty much what it is like now

**Comment by Freddie-Banks** [comment]
With the choice of a colour?

**Comment by LukasJK** [comment]
Ok. Will do tonight

**Comment by Freddie-Banks** [comment]
Great!

**Comment by Freddie-Banks** [comment]
Email notification possible? From an OM to X AM only (purely a thought)
